# Generated by Django 4.2.4 on 2023-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=256)),
                ('Caption', models.CharField(max_length=256)),
                ('Details', models.CharField(max_length=1256)),
                ('online', models.BooleanField(default=False)),
                ('Show_on_website', models.BooleanField(default=False)),
            ],
        ),
    ]
