# Generated by Django 4.2.4 on 2023-08-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(null=True, upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Details',
            field=models.TextField(),
        ),
    ]
